-- ============================================================
-- POMS — Purchase Order Management System
-- PostgreSQL Schema + Seed Data
-- ============================================================
-- Run: psql -U postgres -d po_management -f schema.sql
-- Or create the DB first: createdb po_management
-- ============================================================

-- Drop tables in reverse dependency order
DROP TABLE IF EXISTS purchase_order_items CASCADE;
DROP TABLE IF EXISTS purchase_orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS vendors CASCADE;
DROP TYPE IF EXISTS postatus CASCADE;

-- ─────────────────────────────────────────────
-- ENUM: PO Status
-- ─────────────────────────────────────────────
CREATE TYPE postatus AS ENUM ('Pending', 'Approved', 'Completed');


-- ─────────────────────────────────────────────
-- TABLE: vendors
-- ─────────────────────────────────────────────
-- Stores supplier companies. Rating is 0.0 – 5.0 scale.
CREATE TABLE vendors (
    id      SERIAL PRIMARY KEY,
    name    VARCHAR(200) NOT NULL,
    contact VARCHAR(200) NOT NULL,
    rating  NUMERIC(2,1) DEFAULT 0.0 CHECK (rating >= 0 AND rating <= 5)
);

COMMENT ON TABLE vendors IS 'Supplier/vendor master data';
COMMENT ON COLUMN vendors.rating IS 'Vendor performance rating: 0.0 to 5.0';


-- ─────────────────────────────────────────────
-- TABLE: products
-- ─────────────────────────────────────────────
-- Product catalog. SKU (Stock Keeping Unit) must be globally unique.
-- stock_level is reduced atomically when a PO is created.
CREATE TABLE products (
    id          SERIAL PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    sku         VARCHAR(100) NOT NULL UNIQUE,
    unit_price  NUMERIC(12,2) NOT NULL CHECK (unit_price > 0),
    stock_level INTEGER NOT NULL DEFAULT 0 CHECK (stock_level >= 0),
    description TEXT
);

COMMENT ON TABLE products IS 'Product catalog with live stock tracking';
COMMENT ON COLUMN products.sku IS 'Unique Stock Keeping Unit identifier';
COMMENT ON COLUMN products.description IS 'AI-generated marketing description (optional)';


-- ─────────────────────────────────────────────
-- TABLE: purchase_orders
-- ─────────────────────────────────────────────
-- Main PO record. reference_no is auto-generated by the app (PO-YYYYMMDD-XXXX).
-- total_amount INCLUDES 5% tax — calculated and stored at creation time.
-- vendor_id FK ensures vendor must exist before creating a PO.
CREATE TABLE purchase_orders (
    id           SERIAL PRIMARY KEY,
    reference_no VARCHAR(50)  NOT NULL UNIQUE,
    vendor_id    INTEGER      NOT NULL REFERENCES vendors(id) ON DELETE RESTRICT,
    total_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    status       postatus     NOT NULL DEFAULT 'Pending',
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_po_vendor_id   ON purchase_orders(vendor_id);
CREATE INDEX idx_po_status      ON purchase_orders(status);
CREATE INDEX idx_po_created_at  ON purchase_orders(created_at DESC);

COMMENT ON TABLE purchase_orders IS 'Purchase Order headers — one row per PO';
COMMENT ON COLUMN purchase_orders.total_amount IS 'Final total including 5% tax';
COMMENT ON COLUMN purchase_orders.reference_no IS 'App-generated: PO-YYYYMMDD-XXXX';


-- ─────────────────────────────────────────────
-- TABLE: purchase_order_items
-- ─────────────────────────────────────────────
-- Line items linking a PO to products.
-- price is SNAPSHOT of unit_price at order time — preserves historical accuracy
-- even if the product price changes later.
CREATE TABLE purchase_order_items (
    id         SERIAL PRIMARY KEY,
    po_id      INTEGER       NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    product_id INTEGER       NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    quantity   INTEGER       NOT NULL CHECK (quantity > 0),
    price      NUMERIC(12,2) NOT NULL CHECK (price > 0)
);

CREATE INDEX idx_poi_po_id      ON purchase_order_items(po_id);
CREATE INDEX idx_poi_product_id ON purchase_order_items(product_id);

COMMENT ON TABLE purchase_order_items IS 'Line items for each PO — N items per PO';
COMMENT ON COLUMN purchase_order_items.price IS 'Unit price snapshot at time of order creation';


-- ─────────────────────────────────────────────
-- SEED DATA: Vendors
-- ─────────────────────────────────────────────
INSERT INTO vendors (name, contact, rating) VALUES
  ('Acme Industrial Supplies',    'procurement@acme.com',       4.5),
  ('BoltMart Components',         'sales@boltmart.in',          4.0),
  ('Sunrise Electronics Ltd.',    'orders@sunriseelec.com',     3.5),
  ('KraftTech Engineering',       'contact@krafttech.co.in',    5.0),
  ('PrimeSource Materials',       'info@primesource.net',       4.2);


-- ─────────────────────────────────────────────
-- SEED DATA: Products
-- ─────────────────────────────────────────────
INSERT INTO products (name, sku, unit_price, stock_level) VALUES
  ('Industrial Drill Bit Set (10pc)',   'DRILL-SET-10',   2999.00,  120),
  ('High-Tensile Hex Bolt M12',         'BOLT-M12-HT',      45.50, 5000),
  ('Pneumatic Wrench 1/2"',             'WRENCH-PNEU-12', 8750.00,   35),
  ('Safety Gloves (Pair)',              'SAFETY-GLOVE-L',   199.00,  800),
  ('Industrial Lubricant 5L',           'LUBE-IND-5L',     650.00,  200),
  ('Steel Cable 10mm x 50m',            'CABLE-ST-10-50', 3200.00,   60),
  ('Bearing Assembly 6205',             'BEAR-6205',        380.00,  400),
  ('Digital Caliper 150mm',             'CALIB-DIG-150',  1250.00,   90),
  ('Welding Electrode E6013 (1kg)',      'WELD-E6013-1KG',  350.00,  300),
  ('Hydraulic Jack 3-Ton',              'JACK-HYD-3T',   4500.00,   25);


-- ─────────────────────────────────────────────
-- SAMPLE PURCHASE ORDER (for demo)
-- ─────────────────────────────────────────────
INSERT INTO purchase_orders (reference_no, vendor_id, total_amount, status, created_at)
VALUES ('PO-20240101-DEMO', 1, 16065.38, 'Approved', NOW() - INTERVAL '2 days');

INSERT INTO purchase_order_items (po_id, product_id, quantity, price)
VALUES
  (1, 1, 2, 2999.00),   -- 2x Drill Bit Sets
  (1, 4, 10, 199.00),   -- 10x Safety Gloves
  (1, 7, 5, 380.00);    -- 5x Bearings
-- Subtotal: 2*2999 + 10*199 + 5*380 = 5998+1990+1900 = 9888
-- +5% tax = 10382.4  (note: demo total above includes all items at creation)


-- ─────────────────────────────────────────────
-- USEFUL VIEWS (optional but helpful for reporting)
-- ─────────────────────────────────────────────

CREATE OR REPLACE VIEW v_po_summary AS
SELECT
    po.id,
    po.reference_no,
    v.name          AS vendor_name,
    v.contact       AS vendor_contact,
    po.total_amount,
    ROUND(po.total_amount / 1.05, 2)               AS subtotal,
    ROUND(po.total_amount - (po.total_amount/1.05), 2) AS tax_amount,
    po.status,
    po.created_at,
    COUNT(poi.id)   AS item_count
FROM purchase_orders po
JOIN vendors v        ON v.id = po.vendor_id
LEFT JOIN purchase_order_items poi ON poi.po_id = po.id
GROUP BY po.id, v.name, v.contact;

COMMENT ON VIEW v_po_summary IS 'Denormalized PO summary with vendor info and item counts';
